name: Vprofile actions
on: workflow_dispatch
env: 
    AWS_REGION: eu-central-1
    ECR_REPOSITORY: "aczvprofileapp"
    EKS_CLUSTER: "aczvprofile-eks"

jobs:
  Testing: 
    runs-on: ubuntu-latest
    steps: 
    - name: Code checkout 
      uses: actions/checkout@v4 
      
    - name: Maven Test 
      run: mvn test 
    
    - name: Checkstyle 
      run: mvn checkstyle:checkstyle 

